[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
ordered-float = "4.6.0"
priority-queue = "2.1.1"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
