[package]
name = "benchmark"
version = "1.3.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
num_cpus = "1.16.0"
ordered-float = "4.6.0"
priority-queue = "2.1.1"
threadpool = "1.8.1"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
